### ISSUE TITLE
How to enable multi GPU training?

### ISSUE THREAD

**Issue by piseabhijeet** [weixmath/view-GCN#11]
Hi @weixmath 

How do i enable multi-GPU training? I always end up with CUDA ALLOCATION error.

**Comment by weixmath** [comment]
I trained this model on 12G 1080Ti and i think the training is fast enough. Maybe you can modify it by yourself.

**Comment by auniquesun** [comment]
@piseabhijeet @weixmath Hi, the multi-GPU implementation is available [here](https://github.com/auniquesun/view-gcn-ddp) !
