### ISSUE TITLE
I think sample does not reading in this code

### ISSUE THREAD

**Issue by jun-NN** [weixmath/view-GCN#2]
![캡처2](https://user-images.githubusercontent.com/69620840/90103226-2636d680-dd7d-11ea-8228-f99221fe8278.PNG)
![캡처3](https://user-images.githubusercontent.com/69620840/90103259-2d5de480-dd7d-11ea-809d-c855986018c2.PNG)
![캡처4](https://user-images.githubusercontent.com/69620840/90103290-377fe300-dd7d-11ea-8df3-f0fded4809fd.PNG)
Hello Mr. Weixmath I'm a undergraduate student in Korea. 
I saw this paper in CVPR2020. 
I think it was great idea. So I want to implement this code.
I set up the environment to python 3.6 and pytorch 1.0.   
But I think code can't read data label.
Can you suggest a right solution?

**Comment by weixmath** [comment]
Hello！This error is caused by the incorrect data path. Maybe you can change the data path to the absolute path.
