### ISSUE TITLE
Can you provide a 12 view dataset

### ISSUE THREAD

**Issue by payne11** [weixmath/view-GCN#4]
just like the title，can you provide the 12 view dataset which you used in training 

thanks!!!

**Comment by weixmath** [comment]
You can refer to mvcnn, https://github.com/jongchyisu/mvcnn_pytorch

**Comment by payne11** [comment]
感谢您的回复，请问在检索实验部分ShapeNet Core55 多视图数据集，您是自己生成的么？

**Comment by weixmath** [comment]
是的，用mvcnn提供的matlab上的render函数。

**Comment by payne11** [comment]
感谢您的回复：）

**Comment by weixmath** [comment]
shapenet core55的官网有一个计算结果的脚本

**Comment by payne11** [comment]
您好，请问您遇到过这样一个问题么？ shapenet core 55训练数据集中存在着一些.obj在train.csv中找不到对应标签的数据

**Comment by weixmath** [comment]
Yes, i use the 12-view ModelNet40 dataset provided by them.
