### ISSUE TITLE
code for shape retrieval

### ISSUE THREAD

**Issue by guochengqian** [weixmath/view-GCN#6]
Hi @weixmath, 
Thanks for open-sourcing view-GCN. 
Could you please kindly release the code for shape retrieval experiments (on Shrec2017) as well? 

Thank you!

Guocheng

**Comment by ajhamdi** [comment]
Same request here

**Comment by weixmath** [comment]
Hello！You can refer to https://github.com/kanezaki/SHREC2017_track3 for rendering dataset. When training view-GCN, you can only change the label and num_class. Then use the same retrieval setting as rotationnet.

**Comment by auniquesun** [comment]
> Hello！You can refer to https://github.com/kanezaki/SHREC2017_track3 for rendering dataset. When training view-GCN, you can only change the label and num_class. Then use the same retrieval setting as rotationnet.

I have tried the https://github.com/kanezaki/SHREC2017_track3 to get rendered images but **failed**. 

The provided scripts can be executed but repeated an error, and there is no single image generated, as the figure shows.
![206822947-5aa4d7c0-475c-4883-9bec-c8ee10262e4d](https://user-images.githubusercontent.com/25259958/209672606-52354571-94b8-4980-bf40-f41503a152c9.png)

My MatLab version is R2019b, I am not sure whether it is the cause. Can you share your practices or advice? 
It would be appreciated~
