### ISSUE TITLE
How to visualize aggrigated feature

### ISSUE THREAD

**Issue by saber2124** [weixmath/view-GCN#7]
Hi, thank you again for perfect work, I just wonder to know how can I visualize the aggregated feature like here https://openaccess.thecvf.com/content_CVPR_2020/supplemental/Wei_View-GCN_View Based_Graph_CVPR_2020_supplemental.pdf

**Comment by weixmath** [comment]
Hello！You can save the learned features and use t-SNE to visualize.

**Comment by saber2124** [comment]
Thank you for responding, you mean I should save the output of this line of code
pooled_view = torch.cat((pooled_view1, pooled_view2, pooled_view3), 1)

**Comment by saber2124** [comment]
I have even another question, How can we understand what are the last 5 best views tha can represent better the global feature? Is there any way to see the selected best view?
